[build]
  functions = "functions" 
  
[[redirects]]
  from = "/newtoolsapi/*"
  to = "https://toools.netlify.app/.netlify/functions/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/random-word-generator"
  to = "https://contenttools-new-tools-develop.netlify.app/random-word-generator"
  force = true
  status = 200
  
  [[redirects]]
  from = "/random-adjective-generator"
  to = "https://contenttools-new-tools-develop.netlify.app/random-adjective-generator"
  force = true
  status = 200


  [[redirects]]
  from = "/random-sentence-generator"
  to = "https://contenttools-new-tools-develop.netlify.app/random-sentence-generator"
  force = true
  status = 200
  
   
  [[redirects]]
  from = "/getSentencess"
  to = "https://contenttools-new-tools-develop.netlify.app/sentences.json"
  force = true
  status = 200
  
  
  [[redirects]]
  from = "/random-noun-generator"
  to = "https://contenttools-new-tools-develop.netlify.app/random-noun-generator"
  force = true
  status = 200
  
  
  [[redirects]]
  from = "/random-paragraph-generator"
  to = "https://contenttools-new-tools-develop.netlify.app/random-paragraph-generator"
  force = true
  status = 200

  [[redirects]] 
  from = "/getRandomParagraph" 
  to = "https://contenttools-new-tools-develop.netlify.app/paragraph.json" 
  force = true 
  status = 200
 
  [[redirects]]
  from = "/random-letter-generator"
  to = "https://contenttools-new-tools-develop.netlify.app/random-letter-generator"
  force = true
  status = 200
  
  [[redirects]]
  from = "/meta-and-title-checker"
  to = "https://toools.netlify.app/meta-and-title-checker"
  force = true
  status = 200
  
  [[redirects]]
  from = "/website-word-count"
  to = "https://toools.netlify.app/website-word-count"
  force = true
  status = 200
  
  [[redirects]]
  from = "/serp-simulator"
  to = "https://toools.netlify.app/serp-simulator"
  force = true
  status = 200
  
[[redirects]]
  from = "/text-difference-checker"
  to = "https://toools.netlify.app/text-difference-checker"
  force = true
  status = 200
  
  [[redirects]]
  from = "/tools/sitemap.xml"
  to = "https://toools.netlify.app//sitemap.xml"
  force = true
  status = 200
